
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'DIVISION MULTIPLICACION NUMERO PARENTESIS_DER PARENTESIS_IZQ RESTA SUMA\n    expresion : expresion SUMA expresion\n              | expresion RESTA expresion\n              | expresion MULTIPLICACION expresion\n              | expresion DIVISION expresion\n              | PARENTESIS_IZQ expresion PARENTESIS_DER\n              | NUMERO\n    '
    
_lr_action_items = {'PARENTESIS_IZQ':([0,2,4,5,6,7,],[2,2,2,2,2,2,]),'NUMERO':([0,2,4,5,6,7,],[3,3,3,3,3,3,]),'$end':([1,3,9,10,11,12,13,],[0,-6,-1,-2,-3,-4,-5,]),'SUMA':([1,3,8,9,10,11,12,13,],[4,-6,4,4,4,4,4,-5,]),'RESTA':([1,3,8,9,10,11,12,13,],[5,-6,5,5,5,5,5,-5,]),'MULTIPLICACION':([1,3,8,9,10,11,12,13,],[6,-6,6,6,6,6,6,-5,]),'DIVISION':([1,3,8,9,10,11,12,13,],[7,-6,7,7,7,7,7,-5,]),'PARENTESIS_DER':([3,8,9,10,11,12,13,],[-6,13,-1,-2,-3,-4,-5,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expresion':([0,2,4,5,6,7,],[1,8,9,10,11,12,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expresion","S'",1,None,None,None),
  ('expresion -> expresion SUMA expresion','expresion',3,'p_expresion','analizador.py',53),
  ('expresion -> expresion RESTA expresion','expresion',3,'p_expresion','analizador.py',54),
  ('expresion -> expresion MULTIPLICACION expresion','expresion',3,'p_expresion','analizador.py',55),
  ('expresion -> expresion DIVISION expresion','expresion',3,'p_expresion','analizador.py',56),
  ('expresion -> PARENTESIS_IZQ expresion PARENTESIS_DER','expresion',3,'p_expresion','analizador.py',57),
  ('expresion -> NUMERO','expresion',1,'p_expresion','analizador.py',58),
]
